const APP_CONFIG_NAME: 'app' = 'app';
const DATABASE_CONFIG_NAME: 'database' = 'database';
const REDIS_CONFIG_NAME: 'redis' = 'redis';
const SWAGGER_CONFIG_NAME: 'swagger' = 'swagger';
const CACHE_CONFIG_NAME: 'cache' = 'cache';
const AUTH_CONFIG_NAME: 'auth' = 'auth';
const GRPC_CONFIG_NAME: 'grpc' = 'grpc';

export const CONFIG_TOKENS = {
    APP: {
        CONFIG_NAME: APP_CONFIG_NAME,
        NAME: 'APP_NAME',
        PORT: 'APP_PORT',
        BASE_URL: 'APP_BASE_URL',
        GLOBAL_DEFAULT_API_VERSION: 'APP_GLOBAL_DEFAULT_API_VERSION',
        GLOBAL_PREFIX: 'APP_GLOBAL_PREFIX',
        LOCALE: 'APP_LOCALE',
        NODE_ENV: 'NODE_ENV',
        TZ: 'TZ',
    },
    DB: {
        CONFIG_NAME: DATABASE_CONFIG_NAME,
        TYPE: 'DB_TYPE',
        HOST: 'DB_HOST',
        PORT: 'DB_PORT',
        USERNAME: 'DB_USERNAME',
        PASSWORD: 'DB_PASSWORD',
        DATABASE: 'DB_DATABASE',
        AUTO_LOAD_ENTITIES: 'DB_AUTO_LOAD_ENTITIES',
        ENTITIES: [],
    },
    REDIS: {
        CONFIG_NAME: REDIS_CONFIG_NAME,
        HOST: 'REDIS_HOST',
        PORT: 'REDIS_PORT',
        PASSWORD: 'REDIS_PASSWORD',
        DB: 'REDIS_DB',
        KEY_PREFIX: 'REDIS_KEY_PREFIX',
    },
    SWAGGER: {
        CONFIG_NAME: SWAGGER_CONFIG_NAME,
        ENABLE: 'SWAGGER_ENABLE',
        PATH: 'SWAGGER_PATH',
    },
    CACHE: {
        CONFIG_NAME: CACHE_CONFIG_NAME,
        DEFAULT_TTL: 'CACHE_DEFAULT_TTL',
        MAX_ITEMS: 'CACHE_MAX_ITEMS',
        ENABLED: 'CACHE_ENABLED',
    },
    AUTH: {
        CONFIG_NAME: AUTH_CONFIG_NAME,
        JWT_SECRET: 'AUTH_JWT_SECRET',
        JWT_EXPIRATION: 'AUTH_JWT_EXPIRATION',
        JWT_REFRESH_SECRET: 'AUTH_JWT_REFRESH_SECRET',
        JWT_REFRESH_EXPIRATION: 'AUTH_JWT_REFRESH_EXPIRATION',
        SESSION_SECRET: 'AUTH_SESSION_SECRET',
        SESSION_EXPIRATION: 'AUTH_SESSION_EXPIRATION',
        SESSION_ENABLED: 'AUTH_SESSION_ENABLED',
    },
    GRPC: {
        CONFIG_NAME: GRPC_CONFIG_NAME,
        PORT: 'GRPC_PORT',
        HOST: 'GRPC_HOST',
        MAX_MESSAGE_SIZE: 'GRPC_MAX_MESSAGE_SIZE',
        KEEPALIVE_TIME_MS: 'GRPC_KEEPALIVE_TIME_MS',
        KEEPALIVE_TIMEOUT_MS: 'GRPC_KEEPALIVE_TIMEOUT_MS',
    },
} as const;

export const FLAT_CONFIG_TOKENS = {
    APP: CONFIG_TOKENS.APP,
    DATABASE: CONFIG_TOKENS.DB,
    REDIS: CONFIG_TOKENS.REDIS,
    SWAGGER: CONFIG_TOKENS.SWAGGER,
    CACHE: CONFIG_TOKENS.CACHE,
    AUTH: CONFIG_TOKENS.AUTH,
    GRPC: CONFIG_TOKENS.GRPC,
} as const;

export type ConfigToken = (typeof FLAT_CONFIG_TOKENS)[keyof typeof FLAT_CONFIG_TOKENS];
export type ConfigTokenKey = keyof typeof FLAT_CONFIG_TOKENS;
