// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: link.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'link';

export interface GetLinkRequest {
    shortCode: string;
}

export interface GetLinkResponse {
    id: string;
    originalUrl: string;
    shortCode: string;
    userId: string;
}

export interface ValidateLinkRequest {
    shortCode: string;
}

export interface ValidateLinkResponse {
    valid: boolean;
    reason: string;
}

export const LINK_PACKAGE_NAME = 'link';

export interface LinkServiceClient {
    getLink(request: GetLinkRequest): Observable<GetLinkResponse>;

    validateLink(request: ValidateLinkRequest): Observable<ValidateLinkResponse>;
}

export interface LinkServiceController {
    getLink(request: GetLinkRequest): Promise<GetLinkResponse> | Observable<GetLinkResponse> | GetLinkResponse;

    validateLink(
        request: ValidateLinkRequest,
    ): Promise<ValidateLinkResponse> | Observable<ValidateLinkResponse> | ValidateLinkResponse;
}

export function LinkServiceControllerMethods() {
    return function (constructor: Function) {
        const grpcMethods: string[] = ['getLink', 'validateLink'];
        for (const method of grpcMethods) {
            const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
            GrpcMethod('LinkService', method)(constructor.prototype[method], method, descriptor);
        }
        const grpcStreamMethods: string[] = [];
        for (const method of grpcStreamMethods) {
            const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
            GrpcStreamMethod('LinkService', method)(constructor.prototype[method], method, descriptor);
        }
    };
}

export const LINK_SERVICE_NAME = 'LinkService';
